### ISSUE TITLE
Issue #02 - Feature List

### ISSUE THREAD

**Issue by keginzburg** [charles-tyra/sahara#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [X] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
1. Hey Charles, some formatting work is needed for this design document. First off, your order should be as follows:
+ Hosting on Render
+ User Auth
+ Feature 1: Product Listings
+ Feature 2: Cart
+ Feature 3: Reviews/Ratings
+ Feature 4: Search
+ Production README
+ Bonuses
As of now, the formatting has each Feature without numbering as well, so let's add those. Please let me know if you'd like a visual example.
2. For your User Auth MVP, that should unofficially include your Splash Page as that will offer your users a chance to Sign Up or Login. I would also make a note that on unsuccessful sign up or login, errors will be rendered.
3. One of your four Main Features' bullets is a bit sparse and I'd like to see more thought on it: **Search**.
4. Also, your estimated time is putting your work at 9 days (with Render Hosting and Production README being 0.5 days each). We have roughly 14 official days to work on this project, so I would reallocate to estimated time for User Auth, Cart, and Reviews.
5. Last, be sure to indicate which of your Features are CRUD ***cough cough Cart and Reviews***.
Please let me know once you've implemented these corrections/additions. Solid work!

**Comment by charles-tyra** [comment]
One question about Issue #2, what specifically do you mean for a 'Splash Page'

Reallocated time to specific days as I deem might take the most time to figure out, or where I would want to make sure that the functionality for each of those pieces feel clean (User Auth).

Let me know if you have any more feedback on the fleshing out of these feature lists, will take another thoughtful look through in the next few days and think about what is viable and feels feasible - still want to take a browse through amazon and feel out what I can viably include within the time limit.

Also happy to create a list with numbers to more visibly show each of the main features, let me know if you prefer that to my current visual.

**Comment by keginzburg** [comment]
1. Current visual looks good. No need to incorporate numbering as it's very clean.
2. The Splash Page is the very first view that is rendered to a User when they visit an application. For Amazon, it's fairly dense, so your Product Listing Feature will play into that as their Splash shows off Items. But the main draw of a Splash Page is usually to offer a Welcome message and Auth functionality. If you add a short bullet detailing that you'll need to begin Splash Page work during your Auth Feature, then this all will be good!
