### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [charles-tyra/sahara#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table's name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
1. Be sure to include timestamp columns within your tables. Currently missing `created_at` and `updated_at` in all four.
2. Should your `cart` table have some kind of column indicating the quantity of the items in the cart. It currently works as a join between an item and a user. But what if the user is adding 5 of those items to their cart? Maybe a `quantity` column?
3. Should your `owner_id` column be indexed unique? Would that stop your user from being able to show up in your cart table multiple times? What if they added two different items to their cart?
4. Shouldn't your cart `belongs_to` an item? It has a foreign key `item_id` referencing an item in that cart. Maybe the items `has_many` carts.
5. Following that, your `items` table is referring to specific products in Amazon, so it should not have a foreign key pointing to a cart: `cart_id`. See note 4. It should probably not have a `quantity` column either. What is that referring to?
6. Your `items` table could probably use a `description` column to provide more information besides its name.
7. Should your `reviews` table have a unique composite index for `[item_id, author_id]` to stop users from posting multiple reviews on the same item. Or do you want them to be able to review an item several times? Not an error, just something to think about.
8. Additionally, maybe your `reviews` table needs a `title` column. I believe Amazon has you provide a Title and Body for your Review.

**Comment by charles-tyra** [comment]
Thanks for the feedback on all of these, noticed I was missing quite a few things on item specifically and was looking to add product details and description as text datatypes, as well as an image url (possibly a showcase image url link for those extra photos you can click on for the side once you get into the item's show page, but that could be a little bonus to do at the end -- and it may require another table.)

I like the quantity idea for the cart. Specifically talking about quantity in item, I was thinking more for a backend ordering scheme (you can techincally run of out items in stock, but that could be out of scope)

Made the changes you talked about otherwise, feel free to take a look. Will be updating the sample state to match this new information.

**Comment by keginzburg** [comment]
Just a few small notes:

1. Your `items` table still has a `cart_id` in its list of references and indexes. Be sure to remove that.
2. The `image_url` for your items would only serve as a default image. If you wanted to add more images to your items, then we'd need to either create a join table between your `items` table and a completely separate `photos` table. However, we're going to use AWS for photo attachments, which we'll talk about later, so the `image_url` column isn't completely necessary. That being said, we can totally keep it for now.
3. As for the backend ordering scheme, I would say that's out of scope for now, but maybe a Bonus?

Otherwise, this is looking really good! I'll close this issue, but please take a look at my remaining notes.
