### ISSUE TITLE
Issue #05 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [charles-tyra/sahara#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [X] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [X] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
1. Do we want a `PATCH - /api/users/:id` route for the purposes of updating a user's info? Just an idea.
2. Do we want `GET` routes for our `users` for the purposes of showing who has left Reviews?
3. For `carts`, I'm not sure if the `GET /api/carts` route is completely necessary. Thoughts?

**Comment by charles-tyra** [comment]
All of these make sense, thought about carts was trying to fit crud functionality (it was a stretch, would it make more sense to pull off of owner_id?) - will update all accordingly.

**Comment by keginzburg** [comment]
I think upon log in, we could not only pull the relevant user data, but also the cart data associated with them.
